<?php

namespace App\Console\Commands;

use App\Models\Playlist;
use App\Models\Video;
use App\Services\YoutubeService;
use Illuminate\Console\Command;

class GenerateSingleSubtitleFile extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'app:generate-single-subtitle-file';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';

    /**
     * Execute the console command.
     */
    public function handle(YoutubeService $youtubeService)
    {
        $playlistTitle = $this->choice('Which playlist should synchronize?',
            Playlist::all()->pluck('title', 'id')->toArray()
        );

        $playlist = Playlist::where('title', $playlistTitle)->first();

        $videos = Video::where('playlist_id', $playlist->id)->get();

        $progressBar = $this->output->createProgressBar(count($videos));
        $progressBar->start();

        $outputPath = storage_path('app/public/all_subtitles.txt');

        foreach ($videos as $video) {
            $progressBar->advance();

            if (empty($video->subtitles) && $video->subtitles_autogenerated) {
                continue;
            }

            $subtitles = $video->subtitles ?? $video->subtitles_autogenerated;

            $content = "\n\n``` Передача \"{$video->title}\": ````\n\n";
            $content .= $subtitles;

            file_put_contents($outputPath, $content, FILE_APPEND);
        }

        return self::SUCCESS;
    }
}
