<?php

namespace App\Console\Commands;

use App\Models\Playlist;
use App\Models\Video;
use App\Services\YoutubeService;
use Illuminate\Console\Command;
use Storage;

class TmpImportAutogeneratedSubtitles extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'app:tmp-import-subtitles';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Sync subtitles from youtube in all videos of playlist';

    /**
     * Execute the console command.
     */
    public function handle(YoutubeService $youtubeService)
    {
        $playlistTitle = $this->choice('Which playlist should synchronize?',
            Playlist::all()->pluck('title', 'id')->toArray()
        );

        $playlist = Playlist::where('title', $playlistTitle)->first();

        $videos = Video::where('playlist_id', $playlist->id)
            ->whereNull('subtitles_autogenerated')
            ->whereNull('subtitles')
            ->orderBy('id')
            ->get();

        $progressBar = $this->output->createProgressBar(count($videos));
        $progressBar->start();

        $counter = 0;
        foreach ($videos as $video) {
            $progressBar->advance();

            $filePath = Storage::disk('public')->path('subtitles_old/'.$video->youtube_id.'/');

            $pattern = $filePath.'autogenerated-*.vtt';

            $files = glob($pattern);

            if (! empty($files[0])) {
                $video->update(['subtitles_autogenerated' => file_get_contents($files[0])]);
                $counter++;
            }
        }

        $progressBar->finish();

        $this->info('Imported new subtitles - '.$counter);
    }
}
