<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Arr;
use Throwable;
use Typesense\Client;
use Typesense\Exceptions\ObjectNotFound;

class TypesenseCreateIndex extends Command
{
    private const int VECTOR_DIMENSIONS = 768;

    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'typesense:create-index {--force : Drop and recreate the collection if it already exists}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Create the fragments collection in Typesense (optionally replacing the existing collection).';

    /**
     * Execute the console command.
     */
    public function handle(): int
    {
        $client = $this->makeClient();

        if (! $client) {
            return self::FAILURE;
        }

        $schema = $this->fragmentSchema();
        $collectionName = Arr::get($schema, 'name');

        try {
            if ($this->collectionExists($client, $collectionName)) {
                if (! $this->option('force')) {
                    $this->warn(sprintf(
                        'Collection "%s" already exists. Re-run with --force to drop and recreate it.',
                        $collectionName
                    ));

                    return self::SUCCESS;
                }

                $this->line(sprintf('Dropping existing "%s" collection...', $collectionName));
                $client->collections[$collectionName]->delete();
            }

            $client->collections->create($schema);

            $this->info(sprintf('Typesense collection "%s" has been created successfully.', $collectionName));

            return self::SUCCESS;
        } catch (Throwable $exception) {
            report($exception);
            $this->error('Failed to sync Typesense collection: '.$exception->getMessage());

            return self::FAILURE;
        }
    }

    private function makeClient(): ?Client
    {
        $config = config('typesense');

        if (empty($config['api_key'])) {
            $this->error('TYPESENSE_API_KEY is not configured.');

            return null;
        }

        if (empty($config['nodes'])) {
            $this->error('Typesense nodes are not configured (see config/typesense.php).');

            return null;
        }

        return new Client([
            'api_key' => $config['api_key'],
            'nodes' => $config['nodes'],
            'connection_timeout_seconds' => Arr::get($config, 'connection_timeout_seconds', 2),
        ]);
    }

    private function collectionExists(Client $client, string $collectionName): bool
    {
        try {
            $client->collections[$collectionName]->retrieve();

            return true;
        } catch (ObjectNotFound) {
            return false;
        }
    }

    private function fragmentSchema(): array
    {
        return [
            'name' => 'fragments',
            'fields' => [
                ['name' => 'id', 'type' => 'int64'],
                ['name' => 'video_id', 'type' => 'int32'],
                ['name' => 'text', 'type' => 'string'],
                [
                    'name' => 'text_vector',
                    'type' => 'float[]',
                    'num_dim' => self::VECTOR_DIMENSIONS,
                    'optional' => true,
                ],
                ['name' => 'time_string', 'type' => 'string', 'optional' => true],
                ['name' => 'is_autogenerated', 'type' => 'bool'],
                ['name' => 'created_at', 'type' => 'int64', 'optional' => true],
                ['name' => 'updated_at', 'type' => 'int64', 'optional' => true],
            ],
        ];
    }
}
