<?php

namespace App\Services;

use App\Models\Fragment;
use App\Models\Video;

final class FragmentService
{
    public function createFragments(Video $video): void
    {
        if (! empty($video->subtitles)) {
            $fieldName = 'subtitles';
            $isGenerated = false;
        } elseif (! empty($video->subtitles_autogenerated)) {
            $fieldName = 'subtitles_autogenerated';
            $isGenerated = true;
        } else {
            return;
        }

        $fragments = $this->splitSubtitles($video->$fieldName);

        foreach ($fragments as $fragment) {
            Fragment::create([
                'video_id' => $video->id,
                'time_string' => $fragment['time_string'],
                'text' => $fragment['text'],
                'is_autogenerated' => $isGenerated,
            ]);
        }
    }

    public function deleteFragments(Video $video): void
    {
        Fragment::where('video_id', $video->id)->delete();
    }

    protected function splitSubtitles(string $text): array
    {
        $lines = explode("\n", $text);

        $result = [];
        $currentItem = null;

        foreach ($lines as $line) {
            $line = trim($line);

            if (empty($line) || preg_match('/^WEBVTT$|^Kind:|Language:/i', $line)) {
                continue;
            }

            if (preg_match('/(\d{2}:\d{2}(\:\d{2})?\.\d{3}) --> (\d{2}:\d{2}(\:\d{2})?\.\d{3})/', $line, $matches)) {
                if ($currentItem !== null) {
                    $result[] = $currentItem;
                }
                $currentItem = ['time_string' => $matches[1], 'text' => ''];
            } elseif ($currentItem !== null) {
                $currentItem['text'] .= ' '.$line;
            }
        }

        // Добавляем последний элемент
        if ($currentItem !== null) {
            $result[] = $currentItem;
        }

        // Объединяем если есть разрывы предложений
        $resultArray = [];
        $currentText = '';

        foreach ($result as $item) {
            $text = $item['text'];

            // Если текущий текст не пустой и не завершается одним из знаков (. ! ?), добавляем пробел и конкатенируем с новым текстом
            if (! empty($currentText) && ! preg_match('/[.!?]$/', $currentText)) {
                $currentText .= ' ';
            }

            // Конкатенируем текущий текст с новым текстом
            $currentText .= ' '.$text;

            // Если текст завершается одним из знаков (. ! ?), добавляем его в результат и сбрасываем текущий текст
            if (preg_match('/[.!?]$/', $text)) {
                $resultArray[] = [
                    'time_string' => $item['time_string'],
                    'text' => $currentText,
                ];
                $currentText = '';
            }
        }

        return $resultArray;
    }
}
