<x-filament-panels::page>
    <div class="grid flex-1 auto-cols-fr gap-y-1">

        @if($fragments[0]['is_autogenerated'])
            <span class="bg-red-100 text-red-800 text-sm font-medium me-2 px-2.5 py-0.5 rounded dark:bg-red-900 dark:text-red-300">
                ⚠️Внимание! Текст был сгенерирован автоматически с помощью ИИ и некоторые слова могут быть некорректно распознаны из оригинальной речи.
            </span>

        @endif

        @include('filament.read_buttons')

        @foreach($fragments as $fragment)
            <span title="{{ $fragment->time_string }}">{{ $fragment->text }}</span>
        @endforeach

        @include('filament.read_buttons')
    </div>
</x-filament-panels::page>
