<?php

namespace App\Mcp\Tools;

use App\Models\Fragment;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Request;
use Laravel\Mcp\Response;
use Laravel\Mcp\ResponseFactory;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tool;
use Laravel\Mcp\Server\Tools\Annotations\IsIdempotent;
use Laravel\Mcp\Server\Tools\Annotations\IsReadOnly;

#[Name('read_fragment_window')]
#[Description('Returns a readable fragment window and forward/backward navigation IDs exactly like /admin/fragments/{id}/read.')]
#[IsReadOnly]
#[IsIdempotent]
class ReadFragmentWindowTool extends Tool
{
    private const PER_PAGE = 20;

    public function handle(Request $request): Response|ResponseFactory
    {
        $validated = $request->validate([
            'fragmentId' => ['required', 'integer', 'min:1'],
        ]);

        $fragmentId = (int) $validated['fragmentId'];

        $record = Fragment::with('video')->find($fragmentId);

        if ($record === null) {
            return Response::error("Fragment [{$fragmentId}] not found.");
        }

        $fragments = Fragment::query()
            ->where('id', '>=', $record->id)
            ->where('video_id', $record->video_id)
            ->orderBy('id')
            ->take(self::PER_PAGE)
            ->get();

        if ($fragments->isEmpty()) {
            return Response::error("No fragments found for fragment [{$fragmentId}] in its video.");
        }

        $nextId = (int) $fragments->last()->id + 1;
        $prev = (int) $record->id - self::PER_PAGE;
        $prevId = $prev < 0 ? 1 : $prev;

        $window = $fragments->map(static fn (Fragment $fragment): array => [
            'id' => (int) $fragment->id,
            'timeString' => $fragment->time_string,
            'text' => $fragment->text,
        ])->values()->all();

        return Response::structured([
            'record' => [
                'fragmentId' => (int) $record->id,
                'videoId' => (int) $record->video_id,
                'videoTitle' => (string) ($record->video->title ?? ''),
                'readUrl' => $this->readUrl((int) $record->id),
            ],
            'warning' => [
                'isAutogenerated' => (bool) $fragments->first()->is_autogenerated,
                'message' => (bool) $fragments->first()->is_autogenerated
                    ? 'Autogenerated transcript warning: text may contain recognition mistakes.'
                    : null,
            ],
            'navigation' => [
                'windowSize' => self::PER_PAGE,
                'prevId' => $prevId,
                'nextId' => $nextId,
                'prevUrl' => $this->readUrl($prevId),
                'nextUrl' => $this->readUrl($nextId),
            ],
            'fragments' => $window,
            'fragmentCount' => count($window),
        ]);
    }

    public function schema(JsonSchema $schema): array
    {
        return [
            'fragmentId' => $schema->integer()
                ->required()
                ->min(1)
                ->description('Fragment ID from search results used as read entry point.'),
        ];
    }

    public function outputSchema(JsonSchema $schema): array
    {
        return [
            'record' => $schema->object([
                'fragmentId' => $schema->integer()->required(),
                'videoId' => $schema->integer()->required(),
                'videoTitle' => $schema->string()->required(),
                'readUrl' => $schema->string()->required(),
            ])->required(),
            'warning' => $schema->object([
                'isAutogenerated' => $schema->boolean()->required(),
                'message' => $schema->string()->nullable(),
            ])->required(),
            'navigation' => $schema->object([
                'windowSize' => $schema->integer()->required(),
                'prevId' => $schema->integer()->required(),
                'nextId' => $schema->integer()->required(),
                'prevUrl' => $schema->string()->required(),
                'nextUrl' => $schema->string()->required(),
            ])->required(),
            'fragments' => $schema->array()
                ->required()
                ->items(
                    $schema->object([
                        'id' => $schema->integer()->required(),
                        'timeString' => $schema->string()->nullable(),
                        'text' => $schema->string()->required(),
                    ])
                ),
            'fragmentCount' => $schema->integer()->required(),
        ];
    }

    private function readUrl(int $fragmentId): string
    {
        return url("/admin/fragments/{$fragmentId}/read");
    }
}
