<?php

declare(strict_types=1);

use Elastic\Adapter\Indices\Mapping;
use Elastic\Adapter\Indices\Settings;
use Elastic\Migrations\Facades\Index;
use Elastic\Migrations\MigrationInterface;

final class CreateFragments implements MigrationInterface
{
    /**
     * Run the migration.
     */
    public function up(): void
    {
        Index::create('fragments', function (Mapping $mapping, Settings $settings) {

            $mapping->text('text', ['analyzer' => 'russian']);
            $mapping->integer('video_id');
            $mapping->integer('playlist_id');
            $mapping->boolean('is_autogenerated');
        });
    }

    /**
     * Reverse the migration.
     */
    public function down(): void
    {
        Index::dropIfExists('fragments');
    }
}
