<?php

namespace App\Mcp\Servers;

use App\Mcp\Prompts\EvidenceAnswerPrompt;
use App\Mcp\Prompts\InsufficientDataPolicyPrompt;
use App\Mcp\Prompts\SearchWorkflowPrompt;
use App\Mcp\Tools\ReadFragmentWindowTool;
use App\Mcp\Tools\SearchFragmentsTool;
use Laravel\Mcp\Server;
use Laravel\Mcp\Server\Attributes\Instructions;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Attributes\Version;

#[Name('Search Server')]
#[Version('0.0.1')]
#[Instructions(<<<'TEXT'
Use this server to search subtitle fragments and read full context windows.
Treat tool output as the source of truth.
Do not answer from prior model knowledge when tool data is missing.

Recommended tool flow:
1) Call `search_fragments` with `query` and optional parameters (`matchPhrase`, `page`).
2) For deep reading, call `read_fragment_window` using `fragmentId` from search results.
3) Continue reading with `navigation.prevId` / `navigation.nextId`.

Behavior:
- `search_fragments` always searches across all playlists and videos.
- `search_fragments` returns paginated snippets and `readUrl` links.
- `read_fragment_window` returns 20 sequential fragments from the same video.
- If `warning.isAutogenerated=true`, transcript can contain recognition errors.

Prefer structured output fields; avoid scraping `readUrl` pages when tool data is enough.
TEXT)]
class SearchServer extends Server
{
    protected array $tools = [
        SearchFragmentsTool::class,
        ReadFragmentWindowTool::class,
    ];

    protected array $resources = [
        //
    ];

    protected array $prompts = [
        SearchWorkflowPrompt::class,
        EvidenceAnswerPrompt::class,
        InsufficientDataPolicyPrompt::class,
    ];
}
