<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * @property int $id
 * @property string $text
 * @property int $video_id
 * @property string $time_string
 * @property bool $is_autogenerated
 * @property Carbon $created_at
 * @property Carbon $updated_at
 * @property Video $video
 */
class Fragment extends Model
{
    use HasFactory;

    protected $fillable = [
        'text',
        'video_id',
        'time_string',
        'is_autogenerated',
    ];

    public function video(): BelongsTo
    {
        return $this->belongsTo(Video::class);
    }
}
