<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * @property int $id
 * @property string $title
 * @property string $youtube_id
 * @property bool $is_enabled
 * @property string $subtitles
 * @property string $subtitles_autogenerated
 * @property int $playlist_id
 * @property int $duration
 * @property Carbon $created_at
 * @property Carbon $updated_at
 * @property Playlist $playlist
 */
class Video extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'youtube_id',
        'is_enabled',
        'subtitles',
        'subtitles_autogenerated',
        'playlist_id',
        'duration',
        'attachments',
    ];

    protected $casts = [
        'attachments' => 'array',
    ];

    public function playlist(): BelongsTo
    {
        return $this->belongsTo(Playlist::class);
    }
}
