<?php

namespace App\Mcp\Prompts;

use Laravel\Mcp\Request;
use Laravel\Mcp\Response;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Prompt;
use Laravel\Mcp\Server\Prompts\Argument;

#[Name('evidence_answer')]
#[Description('Template for producing answers only from MCP search evidence with strict citations.')]
class EvidenceAnswerPrompt extends Prompt
{
    public function handle(Request $request): Response
    {
        $question = trim((string) $request->get('question', ''));

        $questionBlock = $question !== ''
            ? "Question: {$question}\n\n"
            : '';

        return Response::text($questionBlock.<<<'TEXT'
Build the answer strictly from MCP tool outputs.

Required process:
1) Run `search_fragments` with at least one focused query.
2) Read context using `read_fragment_window` for key fragment IDs.
3) If needed, run additional searches with refined query wording.
4) Only after evidence collection, produce final answer.

Output format:
- Section 1: "Краткий ответ" (2-6 lines).
- Section 2: "Доказательства" with bullet points.
- Each bullet must include citation:
  [fragmentId=..., video="...", time="..."].

Rules:
- Do not include facts that are not confirmed by fragments.
- If evidence conflicts, state both versions and mark uncertainty.
- If `warning.isAutogenerated=true`, note possible recognition errors.
- If evidence is insufficient, do not speculate. Ask for narrower scope or run more searches.
TEXT);
    }

    public function arguments(): array
    {
        return [
            new Argument(
                name: 'question',
                description: 'Optional user question to anchor evidence-based answer generation.',
                required: false,
            ),
        ];
    }
}
