<?php

namespace App\Mcp\Prompts;

use Laravel\Mcp\Request;
use Laravel\Mcp\Response;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Prompt;
use Laravel\Mcp\Server\Prompts\Argument;

#[Name('search_workflow')]
#[Description('Guides the model through the recommended MCP search and read workflow.')]
class SearchWorkflowPrompt extends Prompt
{
    public function handle(Request $request): Response
    {
        $topic = trim((string) $request->get('topic', ''));

        $topicHint = $topic !== ''
            ? "Topic to investigate: {$topic}\n\n"
            : '';

        return Response::text($topicHint.<<<'TEXT'
Follow this workflow with MCP tools:

1) Search:
- Call `search_fragments` with:
  - required: `query`
  - optional: `matchPhrase`, `page`
- Start with `page=1`.
- If needed, fetch more pages by incrementing `page`.
- Search always runs across all playlists and videos.

2) Reading context:
- Pick relevant `fragmentId` from search results.
- Call `read_fragment_window` with this `fragmentId`.
- For next/previous windows, reuse `navigation.nextId` / `navigation.prevId`.

3) Answering:
- Quote snippets from `search_fragments.snippets` for quick relevance checks.
- Use `read_fragment_window.fragments` for full context before conclusions.
- Respect `warning.isAutogenerated`: wording may be imperfect.
TEXT);
    }

    public function arguments(): array
    {
        return [
            new Argument(
                name: 'topic',
                description: 'Optional topic the model should investigate (for example: рак, иммунитет, питание).',
                required: false,
            ),
        ];
    }
}
